# Generated by Django 3.1 on 2020-09-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reciepe',
            new_name='Recipe',
        ),
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='recipe_box.Recipe'),
        ),
    ]
